### ISSUE TITLE
ALPipeline and ALStrategy 

### ISSUE THREAD

**Issue by paulmorio** [RelationRx/pyrelational#23]
We  propose refactoring the code to decouple the functionality of the active learning pipeline from the active learning strategy. This issue is to discuss the development of an `ALPipeline` class.

In principle the proposed `ALPipeline` will succeed the `GenericALStrategy` class in functionality, and serves to help the user decouple the implementation of their strategies from the overall pipeline. The `ALPipeline` will facilitate the communication between

- a DataManager
- a ML model
- an AL strategy
- an oracle (or None for evaluation mode)

The **proposed action** is to:
1. Copy the functionalities of `pyrelational.strategies.GenericALStrategy` to `pyrelational.pipeline.ALPipeline`
2. Adjust the `active_learning_step` function such that it simply calls upon the strategy to perform such a step. Maybe by calling a strategy specific function called `propose()` or `suggest()`
    - This may call for making an interface which strategies should fulfill corresponding to the informativeness measure utilised and the ranking/selection algorithm used after to keep a consistent interface.
    - My only fear is that this decoupling potentially makes it more difficult to implement sophisticated selection algorithms for the strategies without direct access to iteration counts etc recorded by the `ALPipeline` in this situation --- without requiring the AL strategy send a message to the `ALPipeline`, or requiring the user to augment the `ALPipeline` and overriding the `active_learning_step()` to provide arguments to the selection algorithm.

Happy to discuss!

**Comment by thomasgaudelet** [comment]
I was thinking about the second point to your second point.
One possible solution would be on pipeline side to have the call to the ALStrategy pass both model and dataset but checking which one the ALStrategy expect at call time. Like torchmetrics handles metric updates with a filter_kwargs https://github.com/Lightning-AI/metrics/blob/1ab660e47890b3273c313458d3c39ff698810857/src/torchmetrics/collections.py#L183. Let's discuss

**Comment by thomasgaudelet** [comment]
adressed in PR #33
