### ISSUE TITLE
[Feature] New logger for queries and history.

### ISSUE THREAD

**Issue by paulmorio** [RelationRx/pyrelational#38]
**Is your feature request related to a problem? Please describe.**
Currently, logging is done by two dictionaries in the upcoming Pipeline classes: `query_history` and `log_labelled_by`. This leads to some code readability issues and difficulty maintaining. They also are limited in what they log. `query_history` stores the observation id along with the iteration at which it was labelled, whilst the `log_labelled_by` stores the tag. We could supercede both with a better name and data structure which stores both of these things.

**Describe the solution you'd like**
It would be great if the logging could be handled by a new class that can also interface with common ML monitoring packages such as WandDB and MLFlow.

**Describe alternatives you've considered**
None

**Comment by thomasgaudelet** [comment]
addressed in PR #58

**Comment by jlotthammer** [comment]
Hi, very interesting and well put together project here. I'm looking for documentation on how to log to Wandb with pyrelational. I found this post mentioning supporting that here, but I couldn't find how to perform this. How's this performed in the current interface?

Thanks so much!
