### ISSUE TITLE
[Feature] mypy support 

### ISSUE THREAD

**Issue by thomasgaudelet** [RelationRx/pyrelational#41]
**Is your feature request related to a problem? Please describe.**
Currently proper typing checks are missing from the repository. 

**Describe the solution you'd like**
We propose to add mypy check in the github action workflow and as part of pre-commit.

**Additional context**
This likely will require changes across repo to clarify typing and satisfy requirements.
Furthermore, we propose that this should be accompanied by a review of current typing in order to make the package as flexible as possible (e.g. in places a List is required, while technically any Iterable should be supported).

**Comment by alicerdv** [comment]
`RegressionStrategy` has an input to the scoring function called x, whereas `ClassificationStrategy` does not, so there should be consistency between these two. This may cause issues for mypy if liskov is broken

**Comment by thomasgaudelet** [comment]
addressed in PR #65
