### ISSUE TITLE
[Feature] Ability to set target attribute name by user

### ISSUE THREAD

**Issue by paulmorio** [RelationRx/pyrelational#42]
**Is your feature request related to a problem? Please describe.**
Currently the data_manager.set_target_value() method relies on the fact that we have covered the different way attribute names for target values ("y", "targets", etc.). However, it would be nice to allow the user to reference their own attr when they create integrate their own datasets. 

**Describe the solution you'd like**
A potential solution would be to force the user to use the `.x` and `.y` pattern used in most of our datasets to reference observations and target tensors respectively. A somewhat more difficult though ultimately similar solution would be to allow the user to specify these, and the subsequent methods would take these into account.

**Comment by thomasgaudelet** [comment]
addressed in PR #86
