### ISSUE TITLE
[Feature] Attribute setting calls moved within class

### ISSUE THREAD

**Issue by alicerdv** [RelationRx/pyrelational#48]
**Is your feature request related to a problem? Please describe.**
Currently, some attributes of an object are set directly within the pipeline. Eg self.model.current_model = None is set in theoretical_performance method of AL pipeline

**Describe the solution you'd like**
Attributes like this should be methods of the class eg in the example described above, reset_current_model() should be a method in the model class

**Additional context**
Link to comment where this was mentioned: https://github.com/RelationRx/pyrelational/pull/33#discussion_r1048718624

**Comment by thomasgaudelet** [comment]
addressed in PR #83
