### ISSUE TITLE
[Feature] simplify method names

### ISSUE THREAD

**Issue by thomasgaudelet** [RelationRx/pyrelational#56]
**Is your feature request related to a problem? Please describe.**
Names of method tend to be a bit long and redundant (e.g. active_learning_step in an active learning strategy)

**Describe the solution you'd like**
Proposal is to simplify names across the board, e.g.

- active_learning_step -> step
- active_learning_update -> update
- full_active_learning_run -> run
- etc.

**Comment by alicerdv** [comment]
active_learning_step (in Strategy) -> filtered_call

**Comment by paulmorio** [comment]
Looking at the main modules I focused on the public methods which may warrant some discussion for this. To me it seems that most modules are fine, but there are inconsistencies or improvements to be made in the `DataManager` and `Pipeline` classes. 

I list the all the public methods below.

`DataManager`

- set_target_value
- get_train_set
- get_validation_set
- get_test_set
- get_train_loader
- get_validation_loader
- get_test_loader
- get_unlabelled_loader
- get_labelled_loader
- process_random
- update_train_labels
- percentage_labelled -> `get_percentage_labelled`
- get_sample
- get_sample_feature_vector
- get_sample_feature_vectors
- get_sample_labels
- create_loader

`Pipeline`
- theoretical_performance
- current_performance
- compute_hit_ratio
- active_learning_step -> `step()`
- active_learning_update -> `suggest()` or `ask()` or `obtain_labels()` as we are suggesting observations to the oracle for annotations
- full_active_learning_run -> `run()`
- performance_history
- log_labelled_by

In most cases they can stay as is, but put them all there for some discussion if there needs to be a common style (like a `get-` prefix for all getters, etc.)

**Comment by thomasgaudelet** [comment]
addressed #85
